#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# Start programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

### Initial setup ###
udiskie &
xbindkeys
xmodmap ~/.Xmodmap
xrdb ~/.Xresources
${HOME}/bin/for_robots/setup_screens.sh

### Setup stylus ###
# Pressure curve
xinput --set-prop "Wacom Pen and multitouch sensor Pen Pen (0)" "libinput Tablet Tool Pressurecurve" 0 0.1 0.9 1.0 1.0 1.0 1.0 1.0

### Start graphical session ###
exec i3
