#!/bin/bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Aliases
alias ls='ls --color -I snap'  # Add colors to ls and hide snap
alias v='nvim'
alias rg='rg --ignore-file ~/.ignore'
alias xclip='xclip -selection c -r' # xclip copies as ctrl-C, without trailing newline
alias mathematica="env LD_PRELOAD='/usr/lib/libfreetype.so /usr/lib/libz.so' vblank_mode=0 mathematica"

# Base16 256-color support
BASE16_SHELL="${XDG_CONFIG_HOME}/base16-shell/"

# Set up Liquid Prompt
source ${XDG_CONFIG_HOME}/liquidprompt/liquidprompt

# Python config
source /usr/bin/virtualenvwrapper.sh
