#!/bin/sh

# Configure monitors
xrandr 	--output DP-2 --mode 3840x2160 --pos 0x1680 --primary \
        --output DP-0 --mode 3840x2160 --pos 3840x0 --rotate left

# Read Xresources
xrdb -merge ${XDG_CONFIG_HOME}/X11/Xresources

# Run startup programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Tell systemd units relying on an X session that they can start
# See: https://superuser.com/questions/759759/writing-a-service-that-depends-on-xorg
systemctl --user import-environment PATH DBUS_SESSION_BUS_ADDRESS DISPLAY
systemctl --no-block --user start xsession.target

# Start the window manager
exec i3
