#
# ~/.bash_profile
# Configures bash login shells.
#

# Set generic environment variables
source ~/.config/shells/generic/env.sh

# bash-specific environment variables
export HISTFILE=${XDG_DATA_HOME}/bash/history

# If interactive, load ~/.bashrc
source ~/.bashrc

# Continue with the generic login shell
source ~/.config/shells/generic/login.sh
